<template>
  <div class="page-container"><el-card shadow="never" class="page-card"><template #header><div class="card-header"><div><el-button text @click="router.push(`/material-library/products/${style?.product_id}/styles`)"><el-icon><ArrowLeft /></el-icon>{{ style?.product_name || '款式库' }}</el-button><span class="card-title">{{ style?.name || '款式素材' }}</span></div><el-select v-model="color" clearable placeholder="按颜色筛选" style="width:150px"><el-option v-for="item in colors" :key="item" :label="item" :value="item" /></el-select></div></template><MaterialUploadDropzone @files="upload" /><div class="image-grid"><div v-for="image in filteredImages" :key="image.id" class="image-item" draggable="true" @dragstart="dragged = image" @dragover.prevent @drop="drop(image)"><img :src="image.previewUrl" :alt="image.display_name" loading="lazy" draggable="false" /><div class="image-name" :title="image.display_name">{{ image.display_name }}</div><div class="image-meta">{{ image.color || '未识别颜色' }}</div><div class="image-actions"><el-button text size="small" @click="rename(image)">重命名</el-button><el-button text size="small" @click="editColor(image)">颜色</el-button><el-button text size="small" type="danger" @click="remove(image)">删除</el-button></div></div></div><el-empty v-if="!loading && !filteredImages.length" description="暂无图片" /></el-card></div>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { ElMessage, ElMessageBox } from 'element-plus'; import { ArrowLeft } from '@element-plus/icons-vue'; import MaterialUploadDropzone from '@/components/material-library/MaterialUploadDropzone.vue'; import { getMaterialImagesApi, uploadMaterialImagesApi, renameMaterialImageApi, updateMaterialImageColorApi, deleteMaterialImageApi, reorderMaterialImagesApi } from '@/api'; import { getFileUrl } from '@/api/upload'
const route = useRoute(); const router = useRouter(); const style = ref(null); const images = ref([]); const colors = ref([]); const color = ref(''); const loading = ref(false); const dragged = ref(null); const filteredImages = computed(() => color.value ? images.value.filter(i => i.color === color.value) : images.value)
function imageUrl(image) { return getFileUrl(image.previewUrl) }
async function load() { loading.value = true; try { const res = await getMaterialImagesApi(route.params.styleId); if (res.code === 0) { style.value = res.data.style; images.value = (res.data.images || []).map(image => ({ ...image, previewUrl: getFileUrl(image.previewUrl) })); colors.value = res.data.colors || [] } } finally { loading.value = false } }
async function upload(files) { const res = await uploadMaterialImagesApi(route.params.styleId, files); if (res.code === 0) { ElMessage.success('上传成功'); load() } else ElMessage.error(res.msg) }
async function rename(image) { const { value } = await ElMessageBox.prompt('请输入图片显示名称', '重命名图片', { inputValue: image.display_name }); const res = await renameMaterialImageApi(image.id, { displayName: value }); if (res.code === 0) load(); else ElMessage.error(res.msg) }
async function editColor(image) { const { value } = await ElMessageBox.prompt('请输入颜色；留空表示取消颜色', '修正图片颜色', { inputValue: image.color || '' }); const res = await updateMaterialImageColorApi(image.id, value); if (res.code === 0) load(); else ElMessage.error(res.msg) }
async function remove(image) { await ElMessageBox.confirm(`确定删除“${image.display_name}”吗？`, '确认删除', { type: 'warning' }); const res = await deleteMaterialImageApi(image.id); if (res.code === 0) { ElMessage.success('已删除'); load() } else ElMessage.error(res.msg) }
async function drop(target) { if (!dragged.value || dragged.value.id === target.id || color.value) return; const next = images.value.slice(); const from = next.findIndex(i => i.id === dragged.value.id); const to = next.findIndex(i => i.id === target.id); next.splice(from, 1); next.splice(to, 0, dragged.value); images.value = next; dragged.value = null; const res = await reorderMaterialImagesApi(route.params.styleId, next.map(i => i.id)); if (res.code !== 0) { ElMessage.error(res.msg); load() } }
onMounted(load)
</script>
<style scoped>.card-header { display:flex; justify-content:space-between; align-items:center; }.card-title { margin-left:12px; }.image-grid { display:grid; grid-template-columns:repeat(auto-fill,minmax(170px,1fr)); gap:16px; margin-top:18px; }.image-item { border:1px solid var(--el-border-color-lighter); border-radius:8px; overflow:hidden; background:var(--el-bg-color); }.image-item img { display:block; width:100%; aspect-ratio:1; object-fit:contain; background:var(--el-fill-color-light); }.image-name { padding:8px 10px 0; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }.image-meta { padding:3px 10px; color:var(--el-text-color-secondary); font-size:12px; }.image-actions { display:flex; padding:0 4px 5px; justify-content:flex-end; }</style>
