<template>
  <div class="page-container"><el-card shadow="never" class="page-card"><template #header><div class="card-header"><div><el-button text @click="router.push('/material-library/products')"><el-icon><ArrowLeft /></el-icon>商品库</el-button><span class="card-title">{{ product?.name || '款式库' }}</span></div><el-button type="primary" @click="createStyle"><el-icon><Plus /></el-icon>新建款式</el-button></div></template><div class="material-grid"><MaterialCard v-for="item in styles" :key="item.id" :name="item.name" :count="item.image_count" :preview-url="item.preview_path ? `/api/material-library/images/${item.preview_path}/preview` : ''" @open="openStyle(item.id)" @command="command => handleCommand(item, command)" /></div><el-empty v-if="!styles.length" description="暂无款式" /></el-card></div>
</template>
<script setup>
import { onMounted, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { ElMessage, ElMessageBox } from 'element-plus'; import { Plus, ArrowLeft } from '@element-plus/icons-vue'; import MaterialCard from '@/components/material-library/MaterialCard.vue'; import { getMaterialProductsApi, getMaterialStylesApi, createMaterialStyleApi, renameMaterialStyleApi, deleteMaterialStyleApi } from '@/api'
const route = useRoute(); const router = useRouter(); const product = ref(null); const styles = ref([])
async function load() { const [p, s] = await Promise.all([getMaterialProductsApi(), getMaterialStylesApi(route.params.productId)]); product.value = (p.data || []).find(x => Number(x.id) === Number(route.params.productId)) || null; if (s.code === 0) styles.value = s.data || [] }
function openStyle(id) { router.push(`/material-library/styles/${id}/images`) }
async function createStyle() { const { value } = await ElMessageBox.prompt('请输入款式名称', '新建款式', { inputPattern: /\S+/, inputErrorMessage: '名称不能为空' }); const res = await createMaterialStyleApi(route.params.productId, { name: value }); if (res.code === 0) { ElMessage.success('创建成功'); load() } else ElMessage.error(res.msg) }
async function handleCommand(item, command) { if (command === 'rename') { const { value } = await ElMessageBox.prompt('请输入新名称', '重命名', { inputValue: item.name }); const res = await renameMaterialStyleApi(item.id, { name: value }); if (res.code === 0) load(); else ElMessage.error(res.msg) } if (command === 'delete') { await ElMessageBox.confirm(`将删除“${item.name}”及其全部图片，是否继续？`, '确认删除', { type: 'warning' }); const res = await deleteMaterialStyleApi(item.id); if (res.code === 0) { ElMessage.success('已删除'); load() } else ElMessage.error(res.msg) } }
onMounted(load)
</script>
<style scoped>.material-grid { display:grid; grid-template-columns:repeat(auto-fill,minmax(220px,1fr)); gap:16px; }.card-header { display:flex; justify-content:space-between; align-items:center; }.card-title { margin-left:12px; }</style>
